
#Thymeleaf hot loading
project:
  base-dir: file:///C:/Users/gyun/IdeaProjects/cellit
spring:
  resources:
    static-locations: ${project.base-dir}/src/main/resources/static/
    cache:
      period: 0
  thymeleaf:
    prefix: ${project.base-dir}/src/main/resources/templates/
    cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true